server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: consumer-ribbon2
management:
    endpoints:
       web:
          exposure:
             include: "*"